print("Justified decimals")
print("|" + format(123.456789, "8.2f") + "|")
print("|" + format(123, "8.2f") + "|")
print("|" + format(123.456789, "<8.2f") + "|")
print("|" + format(123, "<8.2f") + "|")
print()
print("Justified integers")
print("|" + format(123, "8") + "|")
print("|" + format(123, "<8") + "|")
print()
print("Justified strings")
print("|" + format("Hello world!", "20") + "|")
print("|" + format("Hello world!", ">20") + "|")
print("|" + format("Hello world!", "<20") + "|")
print()

print()
input("Press return to continue ...")
